V4.4.0
catawiki/aftership-sdk-ruby pull request #1
Opened 2017-12-06 13:07 UTC by fteem

Not to be merged. We need to review the code here, an open a PR upstream. If the maintainers accept the changes they'll need to bump the version and cut a new gem.

2017-12-06 13:23 UTC, coalwater approved these changes

2017-12-06 13:50 UTC, alex-quiterio approved these changes

2017-12-06 15:56 UTC, nickyp approved these changes

2017-12-06 16:52 UTC, coalwater requested changes

2017-12-06 16:52 UTC, coalwater commented on README.md
> +  - Introduced `Configuration` object that encapsulates any gem configuration, like client `timeout` (in seconds), `headers`, `api_key` and `api_endpoint` (that defaults to `api.aftership.com`)
Actually the timeout is in milliseconds, because you divide by 1000

2017-12-11 14:05 UTC, coalwater approved these changes

2017-12-11 14:09 UTC, merged